### ISSUE TITLE
Performance gets worse when using multiple threads

### ISSUE THREAD

**Issue by zhen-xie** [emstoudenmire/parallelDMRG#3]
Hi,
I try to run parallelDMRG in parallel by using MPI and OpenMP to improve performance, but an issue appears.
First, I configured ITensor for single-thread mode and increased the number of processes on a 48 core machine, the results showed that performance increases.

I set N=10000 in pdmrg.cc and use this command "OMP_NUM_THREADS=1 mpirun -np node ./pdmrg"
Number of processes:1 | 6 | 12 | 18 | 24 | 30 | 36 | 42 | 48
Exec. time (second):  40.9444 | 13.9696 | 8.54459 | 6.75166 | 5.95123 | 5.32633 | 5.07224 | 4.72904 | 4.65764

Second, I configured ITensor for multithread mode and set the number of MPI processes to 1, and increased the number of threads on a 48 core machine, the results showed that performance decreases.
I set N=10000 in pdmrg.cc and use this command "OMP_NUM_THREADS=Num_threads mpirun -np 1 ./pdmrg"
Number of threads:  1 | 6 | 12 | 18 | 24 | 30 | 36 | 42 | 48
Exec. time (second):40.9444 | 192.899 | 244.598 | 325.516 | 409.048 | 492.308 | 569.482 | 685.256 | 746.854

I want to ask is there anything wrong? What do I need to improve the performance of multithreading?

Thanks!
-Zhen

**Comment by emstoudenmire** [comment]
Hi Zhen-Xie,
Thanks for the question (actually for questions like these, the best place to ask is our support forum http://itensor.org/support/). 

In the second situation, when you set OMP_NUM_THREADS to different values, what is most likely happening is that both ITensor and the BLAS you are using are trying to use multiple threads at the same time. For example, if you are using MKL as your BLAS, it looks for the OMP_NUM_THREADS environment variable to determine how many threads it should use. So then we recommend that you set the number of BLAS threads just to 1 (turn off BLAS multithreading). For MKL you would do it like this:
OMP_NUM_THREADS = 8
MKL_NUM_THREADS = 1
Then ITensor would use 8 threads and your MKL BLAS would just run in single threaded mode.

Could you please try this and confirm that by always keeping the BLAS single-threaded but raising the number of ITensor threads that you see a speedup?

Miles

**Comment by emstoudenmire** [comment]
Please also note that we have found that the multi-threading in ITensor gives a nice benefit, but only up to about 6-10 threads. So you may find that even when properly turning the BLAS to single-threaded mode, it is best not to set OMP_NUM_THREADS much larger than around 8 threads.

The exact benefit is highly dependent on the number of sparse blocks in your calculation (and only works at all when you are conserving quantum numbers). Also it depends on the typical size of the sparse blocks, so you have to test out different numbers of threads to see what gives the best results.

**Comment by zhen-xie** [comment]
Thanks for your detailed explanation. I also found that, if the OMP_NUM_THREADS is set to 4-8, we can obtain the best performance. And the optimal thread number varies greatly from case to case with different input sizes. As you said, "the exact benefit is highly dependent on the number of sparse blocks in your calculation", I will keep this in my mind and continue to optimize it.
